services:
  nginx:
    image: jonasal/nginx-certbot:5.4.0-nginx1.27.0
    container_name: nginx
    command: sh -c "touch /etc/letsencrypt/cloudflare.ini && /scripts/start_nginx_certbot.sh"
    env_file:
      - ./config/nginx-certbot.env
    ports:
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - ./config/letsencrypt:/etc/letsencrypt
      - ./nginx-files:/etc/nginx/conf.d
    restart: always
  darknore:
    container_name: darknore
    image: 912988307703.dkr.ecr.us-east-1.amazonaws.com/darknore/pythonv1:v0.5.4
    restart: always
    expose:
      - "5001"
    env_file:
      - ~/env/darknore.env
